### ISSUE TITLE
err = db.Exec("CREATE TABLE blob") fails with "panic: found BLOB, expected identifier at line 1, char "

### ISSUE THREAD

**Issue by joe-getcouragenow** [genjidb/genji#186]
but this is fine

```
err = db.Exec("CREATE TABLE files")
```

Is blob a protected word maybe ?

**Comment by asdine** [comment]
Yes it's a protected keyword, but it shouldn't panic so it's definitely a bug, thanks!

**Comment by joe-getcouragenow** [comment]
Ok thanks. 

so then in 

````

// parseCreateTableStatement parses a create table string and returns a Statement AST object.
--
  | // This function assumes the CREATE TABLE tokens have already been consumed.
  | func (p *Parser) parseCreateTableStatement() (query.CreateTableStmt, error) {
  | var stmt query.CreateTableStmt
  | var err error
  |  
  | // Parse IF NOT EXISTS
  | stmt.IfNotExists, err = p.parseIfNotExists()
  | if err != nil {
  | return stmt, err
  | }
  |  
  | // Parse table name
  | stmt.TableName, err = p.parseIdent()
  | if err != nil {
  | return stmt, err
  | }
  |  
  | // parse field constraints
  | err = p.parseFieldConstraints(&stmt.Info)
  | if err != nil {
  | return stmt, err
  | }
  |  
  | return stmt, nil
  | }



````

you want a check on the Table name being "blob", and return an error if so ?

**Comment by asdine** [comment]
Oh, actually it doesn't panic it returns an error, judging by the title I thought it panic'ed.
Does it panic on your side? If so could you share the output?

If not, then that's the expected behavior, we should not be using protected keywords as identifiers, at least not now. We may in the future, I just prefer waiting the parser to be more mature, otherwise, that's the kind of feature that gets in the way.

**Comment by joe-getcouragenow** [comment]
sure here is reproduction code ...

Just change the TableNameBlob  !!!

CODE:
````

package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"

	"github.com/dgraph-io/badger/v2"
	"github.com/genjidb/genji"
	"github.com/genjidb/genji/document"

	"github.com/genjidb/genji/engine/badgerengine"
)

// Mathematical constants.
const (
	// table names

	//TableNameBlob = "files"
	TableNameBlob = "blob" // THIS FAILS. Nothing else i tried fails so far.

	TableNameUser = "users"
)

func main() {
	// Create a badger engine
	db := makeDb("mydb")
	defer db.Close()

	// Make Schema
	makeSchema(db)

	// Make Data
	insert(db)

	// Query some documents
	query(db)
	query1(db)

	// Insert, Query files
	blob(db)

}

// User ...
type User struct {
	ID      int64
	Name    string
	Age     uint32
	Address struct {
		City    string
		ZipCode string
	}
}

// Blob ...
type Blob struct {
	ID    int64
	Name  string
	Ext   string
	Bytes []byte
	Len   int
}

func makeDb(name string) (db *genji.DB) {
	// Create a badger engine
	ng, err := badgerengine.NewEngine(badger.DefaultOptions(name))
	if err != nil {
		log.Fatal(err)
	}

	// Subscribe access :)
	// ng.DB.Subscribe(ctx context.Context, cb func(kv *KVList) error, prefixes ...[]byte)

	// Pass it to genji
	db, err = genji.New(ng)
	if err != nil {
		log.Fatal(err)
	}

	return db
}

func makeSchema(db *genji.DB) {
	// DO in a transaction
	tx, err := db.Begin(true)
	if err != nil {
		panic(err)
	}
	defer tx.Rollback()

	// Users
	s := fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s", TableNameUser)
	err = tx.Exec(s)
	if err != nil {
		panic(err)
	}
	s = fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_user_name ON %s (name)", TableNameUser)
	err = tx.Exec(s)
	if err != nil {
		panic(err)
	}

	// Files
	s = fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s", TableNameBlob)
	err = tx.Exec(s)
	if err != nil {
		panic(err)
	}

	err = tx.Commit()
	if err != nil {
		err = tx.Rollback()
		panic(err)
	}
}

func insert(db *genji.DB) {
	// Insert some data
	s := fmt.Sprintf("INSERT INTO %s (id, name, age) VALUES (?, ?, ?)", TableNameUser)
	err := db.Exec(s, 10, "foo", 15)
	if err != nil {
		panic(err)
	}

	// Insert some data using document notation
	/*
		err = db.Exec(`INSERT INTO user VALUES {id: 12, "name": "bar", age: ?, address: {city: "Lyon", zipcode: "69001"}}`, 16)
		if err != nil {
			panic(err)
		}
	*/

	// Structs can be used to describe a document
	s = fmt.Sprintf("INSERT INTO %s VALUES ?, ?", TableNameUser)
	err = db.Exec(s, &User{ID: 1, Name: "baz", Age: 100}, &User{ID: 2, Name: "bat"})
	if err != nil {
		panic(err)
	}

}

func query(db *genji.DB) {

	s := fmt.Sprintf("SELECT * FROM %s WHERE id > ?", TableNameUser)
	stream, err := db.Query(s, 1)
	if err != nil {
		panic(err)
	}
	// always close the result when you're done with it
	defer stream.Close()

	// Iterate over the results
	err = stream.Iterate(func(d document.Document) error {
		var u User

		err = document.StructScan(d, &u)
		if err != nil {
			return err
		}

		fmt.Println(u)
		return nil
	})
	if err != nil {
		panic(err)
	}
}

func query1(db *genji.DB) {

	s := fmt.Sprintf("SELECT pk(), name FROM %s", TableNameUser)
	stream, err := db.Query(s)
	defer stream.Close()

	// Iterate over the results
	err = stream.Iterate(func(d document.Document) error {
		var u User

		err = document.StructScan(d, &u)
		if err != nil {
			return err
		}

		fmt.Println(u)
		return nil
	})
	if err != nil {
		panic(err)
	}

}

func blob(db *genji.DB) {

	// Best way apparently is to use genji and store the data in a blob column

	// add a file
	// Open file for reading
	filename := "test.txt"
	file, err := os.Open(filename)
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	data, err := ioutil.ReadAll(file)
	if err != nil {
		log.Fatal(err)
	}

	blob := Blob{}

	fmt.Printf("Data as string: %s\n", data)
	fmt.Println("Number of bytes read:", len(data))

	blob.ID = 001
	blob.Name = file.Name()
	blob.Bytes = data
	blob.Len = len(data)

	fmt.Println(blob)

	s := fmt.Sprintf("INSERT INTO %s VALUES ?", TableNameBlob)
	err = db.Exec(s, &blob)
	if err != nil {
		panic(err)
	}

	// Get the same file back from the DB
	s = fmt.Sprintf("SELECT * FROM %s WHERE id = ?", TableNameBlob)
	d, err := db.QueryDocument(s, &blob.ID)
	if err != nil {
		panic(err)
	}
	var b Blob
	err = document.StructScan(d, &b)
	if err != nil {
		panic(err)
	}

	fmt.Println(b)

	fileout := "testout.txt"
	err = ioutil.WriteFile(fileout, b.Bytes, 0644)
	if err != nil {
		panic(err)
	}

}



````

LOG:
````

# delete DB files
rm -rf mydb
mkdir mydb
go run main.go
badger 2020/09/08 14:47:43 INFO: All 0 tables opened in 0s
badger 2020/09/08 14:47:43 INFO: Storing value log head: {Fid:0 Len:29 Offset:247}
badger 2020/09/08 14:47:43 INFO: [Compactor: 173] Running compaction: {level:0 score:1.73 dropPrefixes:[]} for level: 0
badger 2020/09/08 14:47:43 INFO: LOG Compact 0->1, del 1 tables, add 1 tables, took 15.625416ms
badger 2020/09/08 14:47:43 INFO: [Compactor: 173] Compaction for level: 0 DONE
badger 2020/09/08 14:47:43 INFO: Force compaction on level 0 done
panic: found BLOB, expected identifier at line 1, char 28

goroutine 1 [running]:
main.makeSchema(0xc000182098)
        /Users/apple/workspace/go/src/github.com/joe-getcouragenow/junk/archi/db/badgerdb/genjidb__genji/main.go:109 +0x2f4
main.main()
        /Users/apple/workspace/go/src/github.com/joe-getcouragenow/junk/archi/db/badgerdb/genjidb__genji/main.go:32 +0x70
exit status 2
make: *** [run] Error 1


````

**Comment by asdine** [comment]
Well, it's only panic'ing because your code is panic'ing, isn't it?
Genji returns an error and your code does a `panic()`:

```
// Files
	s = fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s", TableNameBlob)
	err = tx.Exec(s)
	if err != nil {
		panic(err)
	}

```

**Comment by joe-getcouragenow** [comment]
Not if you swap the commented code ?
```
	//TableNameBlob = "files"
	TableNameBlob = "blob" // THIS FAILS. Nothing else i tried fails so far.
```

**Comment by asdine** [comment]
I don't understand, what I'm seeing now is that Genji is not panic'ing, it's returning an error if you use `blob` as a table name. This is the expected behaviour.
Then your code on line 108 does this:
```
	if err != nil {
		panic(err)
	}
```

**Comment by samjewell** [comment]
I was trying the same, but with `VALUE` instead of `BLOB`. I was surprised that ChaiSQL considered this a protected keyword. The README.md for ChaiSQL [says that](https://github.com/chaisql/chai/blob/main/README.md?plain=1#L11):
> ChaiSQL SQL API is compatible with PostgreSQL

Yet if I ask an LLM, I see that:

> 1. VALUE is indeed a keyword in PostgreSQL, but it is classified as a non-reserved keyword[3](https://www.postgresql.org/docs/current/sql-keywords-appendix.html).
> 2. Being a non-reserved keyword means that VALUE has a special meaning in certain contexts, but can still be used as an identifier (like a column or table name) in other contexts[3](https://www.postgresql.org/docs/current/sql-keywords-appendix.html).

Anyway, I found my way here, and clicked your link above, but it's broken. Do you have a link to the genji-sql docs?

> By the way if you really want to use anything an an identifier, you just need to use backquotes: https://genji.dev/docs/genji-sql/lexical-structure/#identifiers

**Comment by samjewell** [comment]
I was trying the same, but with `VALUE` instead of `BLOB`. I was surprised that ChaiSQL considered this a protected keyword. The README.md for ChaiSQL [says that](https://github.com/chaisql/chai/blob/main/README.md?plain=1#L11):
> ChaiSQL SQL API is compatible with PostgreSQL

Yet if I ask an LLM, I see that:

> 1. VALUE is indeed a keyword in PostgreSQL, but it is classified as a non-reserved keyword[3](https://www.postgresql.org/docs/current/sql-keywords-appendix.html).
> 2. Being a non-reserved keyword means that VALUE has a special meaning in certain contexts, but can still be used as an identifier (like a column or table name) in other contexts[3](https://www.postgresql.org/docs/current/sql-keywords-appendix.html).

Anyway, I found my way here, and clicked your link above, but it's broken. Do you have a link to the genji-sql docs?

> By the way if you really want to use anything an an identifier, you just need to use backquotes: https://genji.dev/docs/genji-sql/lexical-structure/#identifiers

Or has that doc page disappeared completely from the Genji docs? I couldn't find it when I searched.

@asdine
