### ISSUE TITLE
panic: unknown operator "!~" / "=~"

### ISSUE THREAD

**Issue by tie** [genjidb/genji#252]
`parser.ParseQuery` panics on the following input:
```
SELECT 0!~
SELECT 0=~
```

The culprits are `scanner.EQREGEX` and `scanner.NEQREGEX` (which are not currently supported).

<details>
<summary>cmd/genji stack trace</summary>

```
goroutine 1 [running]:
github.com/genjidb/genji/sql/parser.(*Parser).parseOperator(0xc00019c380, 0x16f3180, 0xc00019c3c0, 0x0, 0x0)
	github.com/genjidb/genji@v0.7.1/sql/parser/expr.go:136 +0x6ed
github.com/genjidb/genji/sql/parser.(*Parser).ParseExpr(0xc00019c380, 0x16f3180, 0xc00019c3c0, 0x0, 0x0, 0x0, 0x0)
	github.com/genjidb/genji@v0.7.1/sql/parser/expr.go:51 +0x22f
github.com/genjidb/genji/sql/parser.(*Parser).parseResultField(0xc00019c380, 0xc0001aa260, 0x6, 0x1166095, 0xc0001a2210)
	github.com/genjidb/genji@v0.7.1/sql/parser/select.go:91 +0x60
github.com/genjidb/genji/sql/parser.(*Parser).parseResultFields(0xc00019c380, 0x0, 0x0, 0x0, 0xc0001aa260, 0x6)
	github.com/genjidb/genji@v0.7.1/sql/parser/select.go:62 +0x2f
github.com/genjidb/genji/sql/parser.(*Parser).parseSelectStatement(0xc00019c380, 0x4f, 0x0, 0x0)
	github.com/genjidb/genji@v0.7.1/sql/parser/select.go:17 +0x71
github.com/genjidb/genji/sql/parser.(*Parser).ParseStatement(0xc00019c380, 0x4f, 0x0, 0x0, 0x0)
	github.com/genjidb/genji@v0.7.1/sql/parser/parser.go:68 +0x5ae
github.com/genjidb/genji/sql/parser.(*Parser).ParseQuery(0xc00019c380, 0xc00019c380, 0x80, 0xc0001a0680, 0x0, 0x203000)
	github.com/genjidb/genji@v0.7.1/sql/parser/parser.go:51 +0xde
github.com/genjidb/genji/cmd/genji/shell.(*Shell).completer(0xc0000b63c0, 0xc0001aa240, 0xa, 0xa, 0x15a7de0, 0xc0000b6401, 0xc00019c340)
	github.com/genjidb/genji/cmd/genji@v0.7.1/shell/shell.go:373 +0x24f
github.com/c-bata/go-prompt.(*CompletionManager).Update(...)
	github.com/c-bata/go-prompt@v0.2.3/completion.go:69
github.com/c-bata/go-prompt.(*Prompt).Run(0xc0000be400)
	github.com/c-bata/go-prompt@v0.2.3/prompt.go:95 +0x6af
github.com/genjidb/genji/cmd/genji/shell.Run(0xc0000a7720, 0xc0000a7720, 0xc0000b0840)
	github.com/genjidb/genji/cmd/genji@v0.7.1/shell/shell.go:114 +0x357
main.main.func1(0xc0000e8b00, 0x0, 0xc0000b2720)
	github.com/genjidb/genji/cmd/genji@v0.7.1/main.go:52 +0x163
github.com/urfave/cli.HandleAction(0x1563fc0, 0x164d1a8, 0xc0000e8b00, 0xc0000e8b00, 0x0)
	github.com/urfave/cli@v1.22.4/app.go:526 +0x11a
github.com/urfave/cli.(*App).Run(0xc00015c000, 0xc00008e1b0, 0x1, 0x1, 0x0, 0x0)
	github.com/urfave/cli@v1.22.4/app.go:288 +0x649
main.main()
	github.com/genjidb/genji/cmd/genji@v0.7.1/main.go:58 +0x1c7
```
</details>

Found with [go-fuzz](https://github.com/dvyukov/go-fuzz).

**Comment by asdine** [comment]
I think we should adopt a different approach for operators that are not yet supported:

- Either we remove them from the scanner
- Or we ignore them in the `parseOperator` function

**Comment by tie** [comment]
I think we should remove them from scanner for now. The majority of the crashers found by go-fuzz are related to this issue, and I don’t think that parser should ignore unknown operators.

We can always add them back by reverting the commit if we need them later.

**Comment by tie** [comment]
Hm, actually, what would happen if we ignore them `parseOperator`? Is that a parse error?

**Comment by tie** [comment]
Yep, it is a parse error. Then it’s fine to ignore them in `parseOperator`.
