### ISSUE TITLE
panic: interface conversion: error is *strconv.NumError, not *parser.ParseError

### ISSUE THREAD

**Issue by tie** [genjidb/genji#256]
`parser.ParseQuery` panics with the following input and stack trace:

```
UPDATE t SET a[999999999999999999
```

<details>
<summary>Stack trace</summary>

```
panic: interface conversion: error is *strconv.NumError, not *parser.ParseError

goroutine 1 [running]:
github.com/genjidb/genji/sql/parser.(*Parser).parseSetClause(0xc00005e240, 0x56, 0x0, 0x9, 0x0, 0x0)
	/home/runner/work/genji/genji/genji/sql/parser/update.go:65 +0x6c0
github.com/genjidb/genji/sql/parser.(*Parser).parseUpdateStatement(0xc00005e240, 0x5c, 0x0, 0x0)
	/home/runner/work/genji/genji/genji/sql/parser/update.go:28 +0x51d
github.com/genjidb/genji/sql/parser.(*Parser).ParseStatement(0xc00005e240, 0x5c, 0x0, 0x0, 0x0)
	/home/runner/work/genji/genji/genji/sql/parser/parser.go:95 +0x833
github.com/genjidb/genji/sql/parser.(*Parser).ParseQuery(0xc00005e240, 0x5bd440, 0xc00001c0a8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x23, 0xc000018480)
	/home/runner/work/genji/genji/genji/sql/parser/parser.go:70 +0x214
github.com/genjidb/genji/sql/parser.ParseQuery(0x5bd440, 0xc00001c0a8, 0xc000018480, 0x23, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000078e70, ...)
	/home/runner/work/genji/genji/genji/sql/parser/parser.go:41 +0x117
github.com/genjidb/genji/fuzz/sqlparser.Fuzz(0x7f6b0be74000, 0x23, 0x23, 0x4)
	/home/runner/work/genji/genji/genji/fuzz/sqlparser/fuzz.go:13 +0xe9
go-fuzz-dep.Main(0xc000043f70, 0x1, 0x1)
	go-fuzz-dep/main.go:36 +0x1ad
main.main()
	github.com/genjidb/genji/fuzz/sqlparser/go.fuzz.main/main.go:15 +0x52
exit status 2
```
</details>

**Comment by asdine** [comment]
As expected, fuzzing is very useful!

**Comment by tie** [comment]
@goku321 thanks, sure!

The error that causes panic is returned by `strconv.Atoi` called in `(*Parser).parsePath`.
https://github.com/genjidb/genji/blob/f5afd65c91591246d9a5386bf80332649f3c42f9/sql/parser/update.go#L63-L68
https://github.com/genjidb/genji/blob/f5afd65c91591246d9a5386bf80332649f3c42f9/sql/parser/expr.go#L433-L436

**Comment by goku321** [comment]
@tie Should I wrap the error returned by `strconv.Atoi` using `ParseError`:
```
idx, err := strconv.Atoi(lit)
if err != nil {
    return nil, newParseError(lit, []string{integer}, pos)
```
OR do a safe type assertion:
```
if ok := err.(*ParseError); !ok {
    ...
}
```

**Comment by tie** [comment]
@goku321 we should return `newParseError`.

Ideally we should be able to parse integers as `math/big.Int` so that such errors are impossible, but that’s out of the scope for this issue.
