### ISSUE TITLE
Panic on SELECT with LIMIT min(0)/max(0)

### ISSUE THREAD

**Issue by tie** [genjidb/genji#257]
`parser.ParseQuery` panics with the following input and stack trace

```
SELECT * FROM e LIMIT min(0)
SELECT * FROM t OFFSET x(*)
```

<details>
<summary>Stack trace</summary>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x50ec01]

goroutine 1 [running]:
github.com/genjidb/genji/sql/query/expr.(*MinFunc).Eval(0xc0000d7da0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/genji/genji/genji/sql/query/expr/function.go:242 +0x51
github.com/genjidb/genji/sql/parser.selectConfig.ToTree(0x69fb05, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/genji/genji/genji/sql/parser/select.go:261 +0x4ed
github.com/genjidb/genji/sql/parser.(*Parser).parseSelectStatement(0xc0001200f0, 0x55, 0x0, 0x0)
	/home/runner/work/genji/genji/genji/sql/parser/select.go:63 +0x44d
github.com/genjidb/genji/sql/parser.(*Parser).ParseStatement(0xc0001200f0, 0x55, 0x0, 0x0, 0x0)
	/home/runner/work/genji/genji/genji/sql/parser/parser.go:91 +0x8a2
github.com/genjidb/genji/sql/parser.(*Parser).ParseQuery(0xc0001200f0, 0x5bd440, 0xc00001c0a8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a, 0xc00011e080)
	/home/runner/work/genji/genji/genji/sql/parser/parser.go:70 +0x214
github.com/genjidb/genji/sql/parser.ParseQuery(0x5bd440, 0xc00001c0a8, 0xc00011e080, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000043e70, ...)
	/home/runner/work/genji/genji/genji/sql/parser/parser.go:41 +0x117
github.com/genjidb/genji/fuzz/sqlparser.Fuzz(0x7f58e832d000, 0x1a, 0x1a, 0x3)
	/home/runner/work/genji/genji/genji/fuzz/sqlparser/fuzz.go:13 +0xe9
go-fuzz-dep.Main(0xc000043f70, 0x1, 0x1)
	go-fuzz-dep/main.go:36 +0x1ad
main.main()
	github.com/genjidb/genji/fuzz/sqlparser/go.fuzz.main/main.go:15 +0x52
```
</details>

**Comment by goku321** [comment]
I can try my hands on this.

**Comment by tie** [comment]
https://github.com/genjidb/genji/issues/273#issuecomment-711052705
> Seems like related to #257. Aggregation functions should not be allowed outside projection.
> This issue:
> 
> https://github.com/genjidb/genji/blob/8fc7000fe8c8f82ee6d1b2b38f6f3498e5e7f76f/sql/query/expr/function.go#L161-L163
> 
> Issue #257:
> 
> https://github.com/genjidb/genji/blob/8fc7000fe8c8f82ee6d1b2b38f6f3498e5e7f76f/sql/query/expr/function.go#L240-L243
> 
> In both cases `ctx.Document` is `nil`, so possible fix is adding something like
> 
> ```go
> 	if ctx.Document == nil {
> 		return document.Value{}, errors.New("misuse of aggregation function MIN()")
> 	}
> ```
> 
> Also, `min()`/`max()`/etc. can have two different implementation — as aggregation function and as plain function, for example
> 
> ```sql
> genji> SELECT min(9, 1, 8);
> 1
> ```
