### ISSUE TITLE
parser.ParseQuery panic when running SELECT * FROM t OFFSET t(*)

### ISSUE THREAD

**Issue by tie** [genjidb/genji#273]
`parser.ParseQuery` panics with the following input and stack trace.

```
SELECT*FROM t OFFSET.0=t(*)
```

<details>
<summary>Stack trace</summary>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x50ecf1]

goroutine 1 [running]:
github.com/genjidb/genji/sql/query/expr.(*CountFunc).Eval(0xc000067950, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa0, 0x55bf20, ...)
        /home/runner/work/genji/genji/genji/sql/query/expr/function.go:162 +0x51
github.com/genjidb/genji/sql/query/expr.(*simpleOperator).eval(0xc000067980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x60, 0x60, ...)
        /home/runner/work/genji/genji/genji/sql/query/expr/expr.go:85 +0x142
github.com/genjidb/genji/sql/query/expr.cmpOp.Eval(0xc000067980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40c058, 0x60, ...)
        /home/runner/work/genji/genji/genji/sql/query/expr/comparison.go:388 +0x8c
github.com/genjidb/genji/sql/parser.selectConfig.ToTree(0x6a1b14, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/genji/genji/genji/sql/parser/select.go:243 +0x85a
github.com/genjidb/genji/sql/parser.(*Parser).parseSelectStatement(0xc0000678f0, 0x55, 0x0, 0x0)
        /home/runner/work/genji/genji/genji/sql/parser/select.go:63 +0x44d
github.com/genjidb/genji/sql/parser.(*Parser).ParseStatement(0xc0000678f0, 0x55, 0x0, 0x0, 0x0)
        /home/runner/work/genji/genji/genji/sql/parser/parser.go:91 +0x8a2
github.com/genjidb/genji/sql/parser.(*Parser).ParseQuery(0xc0000678f0, 0x5be7a0, 0xc00001c0a8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1b, 0xc000016820)
        /home/runner/work/genji/genji/genji/sql/parser/parser.go:70 +0x214
github.com/genjidb/genji/sql/parser.ParseQuery(0x5be7a0, 0xc00001c0a8, 0xc000016820, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00009fe70, ...)
        /home/runner/work/genji/genji/genji/sql/parser/parser.go:41 +0x117
github.com/genjidb/genji/fuzz.FuzzParseQuery(0x7f62d1891000, 0x1b, 0x1b, 0x3)
        /home/runner/work/genji/genji/genji/fuzz/sqlparser.go:13 +0xe9
go-fuzz-dep.Main(0xc00009ff70, 0x1, 0x1)
        go-fuzz-dep/main.go:36 +0x1ad
main.main()
        github.com/genjidb/genji/fuzz/go.fuzz.main/main.go:15 +0x52
exit status 2
```
</details>

This bug was found by go-fuzz. A bit more human-readable input is
```
SELECT * FROM t OFFSET x(*)
```

**Comment by tdakkota** [comment]
Seems like related to #257. Aggregation functions should not be allowed outside projection.
This issue:
https://github.com/genjidb/genji/blob/8fc7000fe8c8f82ee6d1b2b38f6f3498e5e7f76f/sql/query/expr/function.go#L240-L243
Issue #257:
https://github.com/genjidb/genji/blob/8fc7000fe8c8f82ee6d1b2b38f6f3498e5e7f76f/sql/query/expr/function.go#L161-L163

In both cases `ctx.Document` is `nil`, so possible fix is adding something like 
```go
	if ctx.Document == nil {
		return document.Value{}, errors.New("misuse of aggregation function MIN()")
	}
```

**Comment by tie** [comment]
@tdakkota exactly. I didn’t notice that when I created the issue.

**Comment by tie** [comment]
Closing as a duplicate of #257.
