### ISSUE TITLE
Panic and deadlock on 32-bit platforms due to unaligned atomic operations

### ISSUE THREAD

**Issue by tie** [genjidb/genji#277]
>On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

See https://golang.org/pkg/sync/atomic/#pkg-note-BUG

https://github.com/genjidb/genji/blob/0ca41de8c5604b829f11bca60ccc00dc366ced8e/database/database.go#L23

https://github.com/genjidb/genji/blob/0ca41de8c5604b829f11bca60ccc00dc366ced8e/database/database.go#L126

See also #245 which fixes this issue (though by removing transaction IDs entirely).

<details>
<summary>Stack trace</summary>

```
--- FAIL: TestDriver (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11c70]

goroutine 18 [running]:
testing.tRunner.func1.1(0x3429a8, 0x635d20)
	testing/testing.go:1003 +0x26c
testing.tRunner.func1(0x8d8140)
	testing/testing.go:1006 +0x364
panic(0x3429a8, 0x635d20)
	runtime/panic.go:969 +0x118
runtime/internal/atomic.goXadd64(0x89433c, 0x1, 0x0, 0x8160c0, 0x0)
	runtime/internal/atomic/atomic_arm.go:103 +0x1c
github.com/genjidb/genji/database.(*Database).BeginTx(0x894330, 0x841c08, 0x0, 0x0, 0x0)
	github.com/genjidb/genji/database/database.go:126 +0x104
github.com/genjidb/genji/database.(*Database).Begin(...)
	github.com/genjidb/genji/database/database.go:99
github.com/genjidb/genji/sql/query.Query.Run(0x80e030, 0x1, 0x1, 0x0, 0x0, 0x40f1c0, 0x88c010, 0x894330, 0x64b198, 0x0, ...)
	github.com/genjidb/genji/sql/query/query.go:58 +0x358
github.com/genjidb/genji/sql/driver.stmt.ExecContext(0x80e018, 0x0, 0x80e030, 0x1, 0x1, 0x0, 0x0, 0x40f1c0, 0x88c010, 0x64b198, ...)
	github.com/genjidb/genji/sql/driver/driver.go:210 +0x240
database/sql.ctxDriverStmtExec(0x40f1c0, 0x88c010, 0x40f300, 0x80a180, 0x64b198, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	database/sql/ctxutil.go:65 +0x188
database/sql.resultFromStatement(0x40f1c0, 0x88c010, 0x40ec60, 0x80e028, 0x841dfc, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	database/sql/sql.go:2455 +0xf8
database/sql.(*DB).execDC(0x85a000, 0x40f1c0, 0x88c010, 0x85e050, 0x8306c8, 0x38dbe6, 0x11, 0x0, 0x0, 0x0, ...)
	database/sql/sql.go:1525 +0x1e4
database/sql.(*DB).exec(0x85a000, 0x40f1c0, 0x88c010, 0x38dbe6, 0x11, 0x0, 0x0, 0x0, 0xef4cb001, 0x2f79f8, ...)
	database/sql/sql.go:1486 +0xd0
database/sql.(*DB).ExecContext(0x85a000, 0x40f1c0, 0x88c010, 0x38dbe6, 0x11, 0x0, 0x0, 0x0, 0x6b804, 0x95bb0, ...)
	database/sql/sql.go:1464 +0x98
database/sql.(*DB).Exec(...)
	database/sql/sql.go:1478
github.com/genjidb/genji/sql/driver.TestDriver(0x8d8140)
	github.com/genjidb/genji/sql/driver/driver_test.go:25 +0xe8
testing.tRunner(0x8d8140, 0x3a4bdc)
	testing/testing.go:1054 +0xbc
created by testing.(*T).Run
	testing/testing.go:1105 +0x2d4
FAIL	github.com/genjidb/genji/sql/driver	0.118s
```
</details>

**Comment by tie** [comment]
I think this issue would also manifest itself with GOARCH=386.

**Comment by tie** [comment]
OK, test runners don’t just panic. There is also a deadlock.

- Test calls `(*database.Database).BeginTx`.
- `BeginTx` calls `(*memoryengine.Engine).Begin` which acquires the lock on database.
- `BeginTx` atomically increments `lastTransactionID` and panics due to unaligned access.
- Test calls deferred `Close` method that attempts to acquire database lock.
And it can’t do that because we have an incomplete transaction.

**Comment by goku321** [comment]
Would like to work on this.

**Comment by goku321** [comment]
Can I take this one as well?

**Comment by asdine** [comment]
@goku321 Sure

**Comment by asdine** [comment]
@goku321 While working on #322 I realized that it will automatically fix this bug because it removes the `lastTransactionID`. No need to take of this! Thanks!
